"""Reinicio completo

Revision ID: 6cce35a550cd
Revises: 
Create Date: 2026-02-16 01:04:04.142735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cce35a550cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario')
    op.drop_table('campanas_whatsapp')
    op.drop_table('sync_queue')
    op.drop_table('portal_paciente_accesos')
    op.drop_table('caja_movimientos')
    op.drop_table('facturas_qr')
    op.drop_table('roles')
    with op.batch_alter_table('radiografias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_radiografias_medico'))
        batch_op.drop_index(batch_op.f('idx_radiografias_paciente'))

    op.drop_table('radiografias')
    op.drop_table('cajas')
    op.drop_table('campanas_envios')
    with op.batch_alter_table('sonografias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sonografias_medico'))
        batch_op.drop_index(batch_op.f('idx_sonografias_paciente'))

    op.drop_table('sonografias')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_auditoria_tabla'))
        batch_op.drop_index(batch_op.f('idx_auditoria_usuario'))

    op.drop_table('auditoria')
    with op.batch_alter_table('estudios', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_index(batch_op.f('idx_estudios_categoria'))
        batch_op.drop_index(batch_op.f('idx_estudios_codigo'))
        batch_op.drop_table_comment(
        existing_comment='Catálogo de estudios y servicios ofrecidos'
    )

    with op.batch_alter_table('factura_detalles', schema=None) as batch_op:
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('factura_detalles_factura_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'facturas', ['factura_id'], ['id'])

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_index(batch_op.f('idx_facturas_estado'))
        batch_op.drop_index(batch_op.f('idx_facturas_fecha'))
        batch_op.drop_index(batch_op.f('idx_facturas_ncf'))
        batch_op.drop_index(batch_op.f('idx_facturas_paciente'))
        batch_op.drop_constraint(batch_op.f('facturas_anulada_por_id_fkey'), type_='foreignkey')
        batch_op.drop_table_comment(
        existing_comment='Facturas emitidas con NCF'
    )
        batch_op.drop_column('fecha_anulacion')
        batch_op.drop_column('anulada_por_id')
        batch_op.drop_column('motivo_anulacion')

    with op.batch_alter_table('ncf_secuencias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ncf_secuencias_tipo_comprobante_serie_key'), type_='unique')
        batch_op.drop_table_comment(
        existing_comment='Control de secuencias de NCF según DGII'
    )

    with op.batch_alter_table('orden_detalles', schema=None) as batch_op:
        batch_op.alter_column('orden_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('estudio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_orden_detalles_orden'))
        batch_op.drop_constraint(batch_op.f('orden_detalles_tecnico_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('orden_detalles_orden_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ordenes', ['orden_id'], ['id'])
        batch_op.drop_column('tecnico_id')

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_index(batch_op.f('idx_ordenes_estado'))
        batch_op.drop_index(batch_op.f('idx_ordenes_fecha'))
        batch_op.drop_index(batch_op.f('idx_ordenes_paciente'))
        batch_op.drop_table_comment(
        existing_comment='Órdenes de servicio generadas'
    )

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.alter_column('sexo',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_pacientes_apellido'))
        batch_op.drop_index(batch_op.f('idx_pacientes_cedula'))
        batch_op.drop_index(batch_op.f('idx_pacientes_celular'))
        batch_op.drop_index(batch_op.f('idx_pacientes_codigo'))
        batch_op.drop_index(batch_op.f('idx_pacientes_nombre'))
        batch_op.drop_index(batch_op.f('idx_pacientes_telefono'))
        batch_op.drop_constraint(batch_op.f('pacientes_codigo_paciente_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('pacientes_portal_usuario_key'), type_='unique')
        batch_op.drop_table_comment(
        existing_comment='Registro de pacientes del centro diagnóstico'
    )
        batch_op.drop_column('portal_usuario')
        batch_op.drop_column('portal_password')
        batch_op.drop_column('codigo_paciente')
        batch_op.drop_column('ultimo_acceso_portal')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_index(batch_op.f('idx_pagos_factura'))
        batch_op.drop_index(batch_op.f('idx_pagos_fecha'))
        batch_op.drop_column('caja_id')

    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_index(batch_op.f('idx_resultados_orden_detalle'))
        batch_op.drop_constraint(batch_op.f('resultados_validado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_table_comment(
        existing_comment='Resultados de estudios importados de equipos'
    )
        batch_op.drop_column('valores_referencia')
        batch_op.drop_column('validado_por_id')
        batch_op.drop_column('impreso')
        batch_op.drop_column('interpretacion')
        batch_op.drop_column('fecha_validacion')
        batch_op.drop_column('datos_hl7')
        batch_op.drop_column('datos_dicom')
        batch_op.drop_column('enviado_email')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
        batch_op.drop_constraint(batch_op.f('usuarios_rol_id_fkey'), type_='foreignkey')
        batch_op.drop_column('permisos')
        batch_op.drop_column('especialidad')
        batch_op.drop_column('firma_digital')
        batch_op.drop_column('rol_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firma_digital', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('especialidad', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('usuarios_rol_id_fkey'), 'roles', ['rol_id'], ['id'])
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('resultados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enviado_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('datos_dicom', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('datos_hl7', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_validacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interpretacion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('impreso', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('validado_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('valores_referencia', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Resultados de estudios importados de equipos',
        existing_comment=None
    )
        batch_op.create_foreign_key(batch_op.f('resultados_validado_por_id_fkey'), 'usuarios', ['validado_por_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_resultados_orden_detalle'), ['orden_detalle_id'], unique=False)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caja_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_pagos_fecha'), ['fecha_pago'], unique=False)
        batch_op.create_index(batch_op.f('idx_pagos_factura'), ['factura_id'], unique=False)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_acceso_portal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_paciente', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('portal_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('portal_usuario', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Registro de pacientes del centro diagnóstico',
        existing_comment=None
    )
        batch_op.create_unique_constraint(batch_op.f('pacientes_portal_usuario_key'), ['portal_usuario'])
        batch_op.create_unique_constraint(batch_op.f('pacientes_codigo_paciente_key'), ['codigo_paciente'])
        batch_op.create_index(batch_op.f('idx_pacientes_telefono'), ['telefono'], unique=False)
        batch_op.create_index(batch_op.f('idx_pacientes_nombre'), ['nombre', 'apellido'], unique=False)
        batch_op.create_index(batch_op.f('idx_pacientes_codigo'), ['codigo_paciente'], unique=False)
        batch_op.create_index(batch_op.f('idx_pacientes_celular'), ['celular'], unique=False)
        batch_op.create_index(batch_op.f('idx_pacientes_cedula'), ['cedula'], unique=False)
        batch_op.create_index(batch_op.f('idx_pacientes_apellido'), ['apellido'], unique=False)
        batch_op.alter_column('sexo',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Órdenes de servicio generadas',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_ordenes_paciente'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ordenes_fecha'), ['fecha_orden'], unique=False)
        batch_op.create_index(batch_op.f('idx_ordenes_estado'), ['estado'], unique=False)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('orden_detalles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tecnico_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orden_detalles_orden_id_fkey'), 'ordenes', ['orden_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('orden_detalles_tecnico_id_fkey'), 'usuarios', ['tecnico_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_orden_detalles_orden'), ['orden_id'], unique=False)
        batch_op.alter_column('estudio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orden_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ncf_secuencias', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Control de secuencias de NCF según DGII',
        existing_comment=None
    )
        batch_op.create_unique_constraint(batch_op.f('ncf_secuencias_tipo_comprobante_serie_key'), ['tipo_comprobante', 'serie'])

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_anulacion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('anulada_por_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_anulacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Facturas emitidas con NCF',
        existing_comment=None
    )
        batch_op.create_foreign_key(batch_op.f('facturas_anulada_por_id_fkey'), 'usuarios', ['anulada_por_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_facturas_paciente'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_facturas_ncf'), ['ncf'], unique=False)
        batch_op.create_index(batch_op.f('idx_facturas_fecha'), ['fecha_factura'], unique=False)
        batch_op.create_index(batch_op.f('idx_facturas_estado'), ['estado'], unique=False)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))

    with op.batch_alter_table('factura_detalles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('factura_detalles_factura_id_fkey'), 'facturas', ['factura_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('factura_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('estudios', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Catálogo de estudios y servicios ofrecidos',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_estudios_codigo'), ['codigo'], unique=False)
        batch_op.create_index(batch_op.f('idx_estudios_categoria'), ['categoria_id'], unique=False)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))

    op.create_table('auditoria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tabla', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("accion::text = ANY (ARRAY['crear'::character varying, 'actualizar'::character varying, 'eliminar'::character varying, 'ver'::character varying]::text[])", name=op.f('auditoria_accion_check')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('auditoria_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('auditoria_pkey'))
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_auditoria_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_auditoria_tabla'), ['tabla', 'registro_id'], unique=False)

    op.create_table('sonografias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orden_detalle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_estudio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('imagenes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('informe_medico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hallazgos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biometria', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('conclusion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medico_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_estudio', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('fecha_informe', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], name=op.f('sonografias_medico_id_fkey')),
    sa.ForeignKeyConstraint(['orden_detalle_id'], ['orden_detalles.id'], name=op.f('sonografias_orden_detalle_id_fkey')),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name=op.f('sonografias_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sonografias_pkey'))
    )
    with op.batch_alter_table('sonografias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sonografias_paciente'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_sonografias_medico'), ['medico_id'], unique=False)

    op.create_table('campanas_envios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campana_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numero_telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mensaje_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas_whatsapp.id'], name=op.f('campanas_envios_campana_id_fkey')),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name=op.f('campanas_envios_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campanas_envios_pkey'))
    )
    op.create_table('cajas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('cajas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('numero_caja', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_apertura', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('fecha_cierre', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('monto_apertura', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('monto_cierre', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'abierta'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notas_apertura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notas_cierre', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("estado::text = ANY (ARRAY['abierta'::character varying, 'cerrada'::character varying]::text[])", name='cajas_estado_check'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='cajas_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cajas_pkey'),
    sa.UniqueConstraint('numero_caja', name='cajas_numero_caja_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('radiografias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orden_detalle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_estudio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('region_anatomica', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('imagen_original', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imagen_procesada', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('formato', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ancho', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('informe_medico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hallazgos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conclusion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medico_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_toma', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('fecha_informe', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['usuarios.id'], name=op.f('radiografias_medico_id_fkey')),
    sa.ForeignKeyConstraint(['orden_detalle_id'], ['orden_detalles.id'], name=op.f('radiografias_orden_detalle_id_fkey')),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name=op.f('radiografias_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('radiografias_pkey'))
    )
    with op.batch_alter_table('radiografias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_radiografias_paciente'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_radiografias_medico'), ['medico_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('nombre', name='roles_nombre_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('facturas_qr',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigo_qr', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url_acceso', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_generacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('accesos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], name=op.f('facturas_qr_factura_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('facturas_qr_pkey')),
    sa.UniqueConstraint('codigo_qr', name=op.f('facturas_qr_codigo_qr_key'))
    )
    op.create_table('caja_movimientos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caja_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_movimiento', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('concepto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('pago_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("tipo_movimiento::text = ANY (ARRAY['ingreso'::character varying, 'egreso'::character varying, 'apertura'::character varying, 'cierre'::character varying]::text[])", name=op.f('caja_movimientos_tipo_movimiento_check')),
    sa.ForeignKeyConstraint(['caja_id'], ['cajas.id'], name=op.f('caja_movimientos_caja_id_fkey')),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], name=op.f('caja_movimientos_pago_id_fkey')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('caja_movimientos_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('caja_movimientos_pkey'))
    )
    op.create_table('portal_paciente_accesos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_acceso', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dispositivo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], name=op.f('portal_paciente_accesos_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('portal_paciente_accesos_pkey'))
    )
    op.create_table('sync_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tabla', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('datos', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('intentos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('error_mensaje', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint("estado::text = ANY (ARRAY['pendiente'::character varying, 'procesando'::character varying, 'completado'::character varying, 'error'::character varying]::text[])", name=op.f('sync_queue_estado_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_queue_pkey'))
    )
    op.create_table('campanas_whatsapp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_programada', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'pendiente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('total_enviados', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_fallidos', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('usuario_creador_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], name=op.f('campanas_whatsapp_usuario_creador_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campanas_whatsapp_pkey'))
    )
    op.create_table('inventario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unidad_medida', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cantidad_actual', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('cantidad_minima', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('costo_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('proveedor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fecha_vencimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('lote', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventario_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('inventario_codigo_key'))
    )
    # ### end Alembic commands ###
